%YAML:1.0
# Calibration Params for M2DGR
# All Translation stated in meters

# 
#   -------------  Sensor Topics  -------------  
# 

# velodyne lidar 
point_cloud_topic: "/velodyne_points"

# Handsfree IMU (9-axis)
imu_topic: "/handsfree/imu"
mag_topic: "/handsfree/mag"

# VI-sensor (pinhole color d435i)
image_topic: "/camera/color/image_raw/compressed"
imu_topic: "/camera/imu"

# fish-eye camera
left_image_topic: "/camera/left/image_raw/compressed"
right_image_topic: "/camera/right/image_raw/compressed"
midleft_image_topic: "/camera/third/image_raw/compressed"
midright_image_topic: "/camera/fourth/image_raw/compressed"
backleft_image_topic: "/camera/fifth/image_raw/compressed"
backright_image_topic: "/camera/sixth/image_raw/compressed"

# sky-pointing camera
sky_pointing_image_topic: "/camera/head/image_raw/compressed"

# infrared camera
image_topic: "/thermal_image_raw"

# event camera
event_topic: "/dvs_rendering/compressed"
imu_topic: "/dvs/imu"

# GNSS recevier
gnss_topic: /ublox/*

# 
#  -------------  Extrinsic and Intrinsic  -------------  
# 

#  --- velodyne lidar --- 
N_SCAN: 32
Horizon_SCAN: 1800
ang_res_x: 0.2 
ang_res_y: 1.333
ang_bottom: 30.67
groundScanInd: 20

#  --- Handsfree IMU (9-axis) --- 
acc_n: 3.7686306102624571e-02
gyr_n: 2.3417543020438883e-03
acc_w: 1.1416642385952368e-03
gyr_w: 1.4428407712885209e-05
extrinsicRotation: !!opencv-matrix # Transform from imu to Lidar imu_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [  1., 0., 0., -0.27255,
            0., 1, 0., 0.00053, 
            0., 0., 1., -0.17954,
            0., 0., 0., 1. ]

#  --- Xsens IMU (9-axis) --- 
acc_n: 1.2820343288774358e-02
gyr_n: 2.1309311394972831e-03
acc_w: 1.3677912958097768e-03
gyr_w: 3.6603917782528627e-05
extrinsicRotation: !!opencv-matrix # Transform from imu to Lidar imu_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [  1., 0., 0., 0.15905,
            0., 1, 0., 0.00067, 
            0., 0., 1., -0.16824,
            0., 0., 0., 1. ]

#  --- VI-sensor (pinhole color d435i) --- 
#  Camera Intrinsic and Extrinsic
model_type: PINHOLE
image_width: 640
image_height: 480
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: 0.148000794688248
   k2: -0.217835187249065
   p1: 0
   p2: 0
projection_parameters:
   gamma1: 617.971050917033
   gamma2: 616.445131524790
   u0: 327.710279392468
   v0: 253.976983707814
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [  0., 0., 1., 0.30456,
            -1, 0., 0., 0.00065,
            0., -1, 0., 0.65376,
            0., 0., 0., 1. ]
#  IMU Intrisic and Extrinsic
acc_n: 2.6848761610624401e-02
gyr_n: 2.4710787075320089e-03
acc_w: 8.5216274964016023e-04
gyr_w: 1.7963145905200798e-05
extrinsicRotation: !!opencv-matrix # Transform from imu to Lidar imu_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [  0., -1, 0., 0.18,
            1., 0., 0., 0.01,
            0., 0., 1., 0.66,
            0., 0., 0., 1. ]

#  --- fish-eye camera --- 
#  Left Camera Intrinsic and Extrinsic
model_type: MEI
image_width: 1280
image_height: 1024
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: 0.148000794688248
   k2: -0.217835187249065
   p1: -0.021968993685891842
   p2: 0.007442211946112636
projection_parameters:
   gamma1: 540.645056202188
   gamma2: 539.8545023658869
   u0: 626.4125666883942
   v0: 523.947634226782
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [ 0., 0., 1., 0.24221,
          -1., 0., 0., 0.16123,
          0., -1., 0., -0.16711,
          0., 0., 0., 1. ]

#  Right Camera Intrinsic and Extrinsic
model_type: MEI
image_width: 1280
image_height: 1024
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: -0.07147685334620411
   k2: 0.006423830171528276
   p1: -0.02354604292216998
   p2: 0.009181757660952325
projection_parameters:
   gamma1: 540.6832252229977
   gamma2: 539.3921307247979
   u0: 632.9173957218305
   v0: 503.3766864767991
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [  0., 0., 1., 0.30456,
            -1, 0., 0., 0.00065,
            0., -1, 0., 0.65376,
            0., 0., 0., 1. ]

#  Mid-left Camera Intrinsic and Extrinsic
model_type: MEI
image_width: 1280
image_height: 1024
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: -0.061526128889893804
   k2: -0.00867447574360461
   p1: -0.00984399833727642
   p2: 0.004810173767131135
projection_parameters:
   gamma1: 538.3154329292029
   gamma2: 537.4277766778052
   u0: 632.4020370259001
   v0: 509.3609761132556
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., 0.00109,
          0., 0., 1., 0.16004,
          0., -1., 0., -0.16718,
          0., 0., 0., 1. ]

#  Mid-Right Camera Intrinsic and Extrinsic
model_type: MEI
image_width: 1280
image_height: 1024
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: -0.06329338788105426
   k2: -0.005282288794043655
   p1: -0.01439687642303018
   p2: 0.006593296524853555
projection_parameters:
   gamma1: 537.2294180909289
   gamma2: 536.6425889117285
   u0: 635.5687263167875
   v0: 491.9422582452684
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [ -1., 0., 0., 0.00021,
          0., 0., -1., -0.16013,
          0., -1., 0., -0.16674,
          0., 0., 0., 1. ]

#  Back-left Camera Intrinsic and Extrinsic
model_type: MEI
image_width: 1280
image_height: 1024
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: -0.057504608980455875
   k2: -0.03555561603037192
   p1: 0.030555976552383957
   p2: -0.014358151534147164
projection_parameters:
   gamma1: 539.834690518987
   gamma2: 538.7141533225924
   u0: 630.8171732844409
   v0: 501.86380820583685
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [ 0., 0., -1, -0.24175,
          1., 0., 0., 0.16031,
          0., -1., 0., -0.16715,
          0., 0., 0., 1. ]

#  Back-Right Camera Intrinsic and Extrinsic
model_type: MEI
image_width: 1280
image_height: 1024
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: -0.06681929469733765
   k2: -0.005533273650165602
   p1: -0.006167142895316966
   p2: 0.0018089751112068567
projection_parameters:
   gamma1: 543.4124571628414
   gamma2: 542.2071506815953
   u0: 642.967852391304
   v0: 504.2993692252895
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [ 0., 0., -1., -0.24313,
          1., 0., 0., -0.16037,
          0, -1, 0, -0.16689,
          0., 0., 0., 1. ]

#  --- thermal camera --- 
model_type: PINHOLE
image_width: 640
image_height: 512
mirror_parameters: # unnecessary when model type is pinhole
   xi: 0
distortion_parameters:
   k1: -0.436107594318055
   k2: 0.166413618922992
   p1: 0
   p2: 0
projection_parameters:
   gamma1: 435.836180277211
   gamma2: 435.909430631362
   u0: 324.452753232850
   v0: 255.554320082190
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [ 0., 0., 1., 0.30456,
          -1, 0., 0., 0.17065,
          0., -1, 0., 0.65376,
          0., 0., 0., 1. ]

#  --- event camera --- 
model_type: 
image_width: 640
image_height: 480
extrinsicRotation: !!opencv-matrix # Transform from camera to Lidar cam_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [ 0., 0., 1, 0.30474,
          -1, 0., 0., -0.17065,
          0., -1, 0., 0.65376,
          0., 0., 0., 1. ]

#  --- UBLOX, Xsens GNSS --- 
extrinsicRotation: !!opencv-matrix # Transform from gnss receiver to Lidar gnss_T_lidar
   rows: 4
   cols: 4
   dt: d
   data: [  1., 0., 0., -0.09825,
            0., 1, 0., 0.00582, 
            0., 0., 1., 0.72673,
            0., 0., 0., 1. ]